### PR TITLE
Added Youbora Configurability

### PR DESCRIPTION
**Pull request by m-kalaleeb**

### CODE REVIEW

**Comment by MycujooMats** [comment]
Could you rename it from `youboraAccountCode` to `analyticsAccount`? This is for two reasons:
- The web already uses this, so it's good to be consistent;
- In the future we might want to use this property in combination with another property for setting the analytics provider (Youbora is just one option, there's others)

Once this addressed, I think we can merge it (I didn't actually test it, but I assume you did @m-kalaleeb ). We'll need to get this in a new release either this week, or early next week.

**Comment by m-kalaleeb** [comment]
I have tested it, on 3 different code sources 

And, the renaming is done @MycujooMats

**Comment by MycujooMats** [comment]
> I have tested it, on 3 different code sources
> 
> And, the renaming is done @MycujooMats

Thanks. I still see some unchanged references though, e.g. `MLS_YOUBORA_ACCOUNT`

**Comment by m-kalaleeb** [comment]
Now, it's fixed 😄  @MycujooMats

**Comment by MycujooMats** [comment]
> Now, it's fixed 😄 @MycujooMats

There's still a few references in the docs, and a method called `grabYouboraKeyFromManifest`, but I'll approve it.

**Review by MycujooMats — APPROVED** [review]

**Pull request merged**
